#! /bin/sh

sxhkd &
picom &
sh ~/.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#feh --bg-fill ~/.config/wallpapers/chemistry_drugs.png
hsetroot -solid '#161821' &
dunst &

wmname LG3D

bspc monitor -d I II III IV V VI

bspc config normal_border_color '#6b7089'
bspc config active_border_color '#d2d4de'
bspc config focused_border_color '#d2d4de'

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Termite state=floating follow=on
bspc rule -a URxvt state=floating follow=on
bspc rule -a Thunar state=floating follow=on
bspc rule -a SplashScreen state=floating follow=on
bspc rule -a Gnome-calculator state=floating follow=on
bspc rule -a Gnome-disks state=floating follow=on
bspc rule -a Lxappearance state=floating follow=on
bspc rule -a Ristretto state=floating follow=on
bspc rule -a qBittorrent state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Gnome-system-monitor state=floating follow=on
bspc rule -a zoom state=floating follow=on
bspc rule -a qt5ct state=floating follow=on
bspc rule -a nvim-qt state=floating follow=on
bspc rule -a KeePassXC state=floating follow=on
bspc rule -a "VirtualBox Manager" state=floating follow=on
bspc rule -a Eog  state=floating follow=on
bspc rule -a "Kvantum Manager"  state=floating follow=on
bspc rule -a "Connman-gtk"  state=floating follow=on
bspc rule -a "XTerm"  state=floating follow=on
bspc rule -a "Gufw.py"  state=floating follow=on
bspc rule -a "Tor Browser"  state=floating follow=on
bspc rule -a "torbrowser-launcher"  state=floating follow=on
bspc rule -a "kitty"  state=floating follow=on
