#! /bin/sh

sxhkd &
nm-applet &
picom &
sh ~/.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#hsetroot -solid "#f0f0f0" &
#hsetroot -solid "#282c34" &
feh --bg-fill $HOME/Pictures/mountain.png &
dunst &

wmname LG3D

bspc monitor -d I II III IV V VI

# for light varient
#bspc config normal_border_color '#f0f0f0'
#bspc config active_border_color '#f0f0f0'
#bspc config focused_border_color '#383a42'

# for dark varient
bspc config normal_border_color '#dcdfe4'
bspc config active_border_color '#dcdfe4'
bspc config focused_border_color '#61afef'

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a URxvt state=floating follow=on
bspc rule -a Thunar state=floating follow=on
bspc rule -a SplashScreen state=floating follow=on
bspc rule -a Gnome-calculator state=floating follow=on
bspc rule -a Gnome-disks state=floating follow=on
bspc rule -a Lxappearance state=floating follow=on
bspc rule -a Ristretto state=floating follow=on
bspc rule -a qBittorrent state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Gnome-system-monitor state=floating follow=on
bspc rule -a zoom state=floating follow=on
bspc rule -a qt5ct state=floating follow=on
bspc rule -a nvim-qt state=floating follow=on
bspc rule -a KeePassXC state=floating follow=on
bspc rule -a "VirtualBox Manager" state=floating follow=on
bspc rule -a Eog  state=floating follow=on
bspc rule -a "Kvantum Manager"  state=floating follow=on
bspc rule -a "Connman-gtk"  state=floating follow=on
bspc rule -a "XTerm"  state=floating follow=on
bspc rule -a "Gufw.py"  state=floating follow=on
